import { RoleName, UserStatus, CampaignStatus, PlacementStatus, WithdrawalStatus } from '@prisma/client'; import { db } from '../db/client.js'; import { recordAudit } from './audit.js';
export async function searchUsers(query:string,role?:RoleName){return db.user.findMany({where:{AND:[role?{roles:{some:{role}}}:{}, {OR:[{username:{contains:query}},{firstName:{contains:query}},{telegramId:{contains:query}}]}]},include:{roles:true},take:50});}
export async function getUserProfile(id:string){return db.user.findUniqueOrThrow({where:{id},include:{roles:true,wallet:{include:{transactions:true}},campaigns:true,withdrawals:true,ratingsGiven:true,ratingsReceived:true,auditEvents:true,riskFlags:true}});}
export async function changeUserStatus(actorId:string,userId:string,status:UserStatus){const before=await db.user.findUniqueOrThrow({where:{id:userId},select:{status:true}});const user=await db.user.update({where:{id:userId},data:{status}});await recordAudit({actorId,action:status===UserStatus.BANNED?'USER_BAN':'ADMIN_ACTION',entity:'User',entityId:userId,previousState:before,newState:{status}});return user;}
export async function listCampaigns(filters:{status?:CampaignStatus;platform?:string;objective?:string;advertiserId?:string}){return db.campaign.findMany({where:{status:filters.status,platform:filters.platform as never,objective:filters.objective as never,advertiserId:filters.advertiserId},orderBy:{createdAt:'desc'},take:100,include:{placements:true,moderationLogs:true}});}
export async function getModerationQueue(){return db.campaign.findMany({where:{status:CampaignStatus.PENDING_REVIEW},orderBy:{createdAt:'asc'},take:100,include:{advertiser:{include:{user:true}},advertisements:true}});}
export async function listWithdrawals(status?:WithdrawalStatus){return db.withdrawal.findMany({where:{status},orderBy:{createdAt:'asc'},take:100,include:{user:true,paymentMethod:true}});}
export async function updateWithdrawal(actorId:string,id:string,status:WithdrawalStatus,paymentReference?:string){const before=await db.withdrawal.findUniqueOrThrow({where:{id},select:{status:true}});const w=await db.withdrawal.update({where:{id},data:{status,paymentReference}});await recordAudit({actorId,action:'WITHDRAWAL_DECISION',entity:'Withdrawal',entityId:id,previousState:before,newState:{status,paymentReference}});return w;}
export const placementStates={active:PlacementStatus.PENDING,failed:PlacementStatus.FAILED};
